Repository Puskar-Roy/create-my-api, pull requests merged in 2024-10, with the labels that each got.

#43 Feature/dynamic GitHub stars
  apps/web/components/ui/GIthub-Button.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#56 Fix/hero btn
  apps/main-cli/index.js
  apps/web/components/Words.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#59 [ADD API] : A basic API template for Uploading files and generating Tiny URL's #57
  packages/APIs/Uploading_Files_API/.env.example
  packages/APIs/Uploading_Files_API/.eslintignore
  packages/APIs/Uploading_Files_API/.eslintrc.cjs
  packages/APIs/Uploading_Files_API/.gitignore
  packages/APIs/Uploading_Files_API/.prettierrc
  packages/APIs/Uploading_Files_API/README.md
  packages/APIs/Uploading_Files_API/api/index.ts
  packages/APIs/Uploading_Files_API/package-lock.json
  packages/APIs/Uploading_Files_API/package.json
  packages/APIs/Uploading_Files_API/src/constants.ts
  packages/APIs/Uploading_Files_API/src/controllers/uploadController.ts
  packages/APIs/Uploading_Files_API/src/index.ts
  packages/APIs/Uploading_Files_API/src/routes/index.ts
  packages/APIs/Uploading_Files_API/src/routes/uploadRouter.ts
  packages/APIs/Uploading_Files_API/tests/genURL.postman_collection.json
  packages/APIs/Uploading_Files_API/tsconfig.json
  packages/APIs/Uploading_Files_API/vercel.json
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#60 Add Rust-ActixWeb-Postgres API with Actix-Web, Postgres, and Deadpool connection pooling
  packages/APIs/rust-actixweb-postgres-api/.env.example
  packages/APIs/rust-actixweb-postgres-api/.gitignore
  packages/APIs/rust-actixweb-postgres-api/Cargo.lock
  packages/APIs/rust-actixweb-postgres-api/Cargo.toml
  packages/APIs/rust-actixweb-postgres-api/readme.md
  packages/APIs/rust-actixweb-postgres-api/src/config/db.rs
  packages/APIs/rust-actixweb-postgres-api/src/config/mod.rs
  packages/APIs/rust-actixweb-postgres-api/src/main.rs
  packages/APIs/rust-actixweb-postgres-api/src/models/mod.rs
  packages/APIs/rust-actixweb-postgres-api/src/models/user.rs
  packages/APIs/rust-actixweb-postgres-api/src/routes/mod.rs
  packages/APIs/rust-actixweb-postgres-api/src/routes/user_routes.rs
  packages/APIs/rust-actixweb-postgres-api/src/services/mod.rs
  packages/APIs/rust-actixweb-postgres-api/src/services/user_service.rs
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#65 Added a compiler API #64
  packages/APIs/Compiler_API/.dockerignore
  packages/APIs/Compiler_API/.gitignore
  packages/APIs/Compiler_API/.prettierignore
  packages/APIs/Compiler_API/Dockerfile
  packages/APIs/Compiler_API/README.md
  packages/APIs/Compiler_API/api/index.ts
  packages/APIs/Compiler_API/build.mjs
  packages/APIs/Compiler_API/eslint.config.mjs
  packages/APIs/Compiler_API/package-lock.json
  packages/APIs/Compiler_API/package.json
  packages/APIs/Compiler_API/prettier.config.mjs
  packages/APIs/Compiler_API/src/controllers/compilerController.ts
  packages/APIs/Compiler_API/src/controllers/index.ts
  packages/APIs/Compiler_API/src/index.ts
  packages/APIs/Compiler_API/src/routes/complierRouter.ts
  packages/APIs/Compiler_API/src/routes/mainRouter.ts
  packages/APIs/Compiler_API/test/config.mjs
  packages/APIs/Compiler_API/test/setup.mjs
  packages/APIs/Compiler_API/tsconfig.json
  packages/APIs/Compiler_API/vercel.json
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#69 scroll bar added : Done #62 #63 #67
  apps/web/app/globals.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#45 added cursor animation
  apps/docs/next-env.d.ts
  apps/web/components/ui/container-scroll-animation.tsx
  apps/web/components/ui/custom-cursor.tsx
  apps/web/next-env.d.ts
  package-lock.json
  package.json
  turbo.json
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#80 UI
  apps/web/components/Footer.tsx
  apps/web/components/ui/infinite-effect.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#77 fixed UI inconsistency , issue no. #76
  apps/web/components/Words.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#83 Dev
  apps/web/app/page.tsx
  apps/web/components/BacktoTop.tsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#88 Update README.md
  README.md
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#91 ISSUE #89 (SOLVED) Updated CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#98 ISSUE #97 Updated Footer.tsx
  apps/web/components/Footer.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#100 Issue #99
  apps/web/components/ui/GIthub-Button.tsx
  apps/web/tailwind.config.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#114 Add/crud api
  packages/APIs/Crud_API/.prettierignore
  packages/APIs/Crud_API/.prettierrc
  packages/APIs/Crud_API/package-lock.json
  packages/APIs/Crud_API/package.json
  packages/APIs/Crud_API/readme.md
  packages/APIs/Crud_API/src/app.js
  packages/APIs/Crud_API/src/constants.js
  packages/APIs/Crud_API/src/controllers/resource.controllers.js
  packages/APIs/Crud_API/src/db/index.js
  packages/APIs/Crud_API/src/index.js
  packages/APIs/Crud_API/src/models/models.js
  packages/APIs/Crud_API/src/routes/resource.routes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#113 added scroll progress bar
  apps/web/app/page.tsx
  apps/web/components/ScrollProgress.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#126 [API Improvement] : Dockerize the OnlineBookSales_API #125
  packages/APIs/Crud_API/.prettierignore
  packages/APIs/Crud_API/.prettierrc
  packages/APIs/Crud_API/package-lock.json
  packages/APIs/Crud_API/package.json
  packages/APIs/Crud_API/readme.md
  packages/APIs/Crud_API/src/app.js
  packages/APIs/Crud_API/src/constants.js
  packages/APIs/Crud_API/src/controllers/resource.controllers.js
  packages/APIs/Crud_API/src/db/index.js
  packages/APIs/Crud_API/src/index.js
  packages/APIs/Crud_API/src/models/models.js
  packages/APIs/Crud_API/src/routes/resource.routes.js
  packages/APIs/OnlineBookSales_API/.dockerignore
  packages/APIs/OnlineBookSales_API/Dockerfile
  packages/APIs/OnlineBookSales_API/docker-compose.yaml
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#143 ISSUE #142 (solved)
  apps/web/components/TerminalCard.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#147 added terms and conditions
  apps/web/app/(terms)/terms/page.tsx
  apps/web/components/Footer.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#153 ISSUE #152 (solved) improved code documentation
  apps/web/components/ContactForm.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#148 enhanced scroll to top
  apps/web/components/BacktoTop.tsx
  apps/web/components/style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#162 ISSUE #161 SOLVED Improved Code documentation
  apps/web/components/ScrollProgress.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest
